config/routes.rb
module ::KoeNicoRoutesExtender
  def get_with_finished(path, *args, **kwds)
    fkwds = {}
    fkwds[:action] = "#{kwds[:action]}_finished"
    fkwds[:as] = "#{kwds[:as]}_finished" if kwds[:as]
    get path, *args, **kwds
    get "#{path}/finished", *args, **(kwds.merge(fkwds))
  end
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root controller: 'top_page', action: 'index'

  scope '/programs', controller: 'programs', as: 'programs' do

    extend ::KoeNicoRoutesExtender

    get_with_finished '/',          action: 'index'
    get_with_finished '/favorites', action: 'index_favorites'

    #get '/all',       action: 'index_all'

    get_with_finished '/v/:names',
      action: 'search_by_voiceactors',
      as: :search_by_voiceactors

    get_with_finished '/tag/:tag',
      action: 'search_by_tag',
      as: :search_by_tag
  end

  get '/voiceactors', to: 'voiceactor#index'

  # TODO: make restful
  get    '/profile/favorites', to: 'users#list_favorites'
  put    '/profile/favorites/:name', to: 'users#add_favorite', as: 'profile_favorite'
  delete '/profile/favorites/:name', to: 'users#delete_favorite'

  scope '/admin' do
    get  'manage_voiceactors/import_yaml', to: 'manage_voiceactors#import_yaml_form'
    post 'manage_voiceactors/import_yaml', to: 'manage_voiceactors#import_yaml'

    resources :manage_voiceactors
    resources :contacts

    get 'programs/:live_id', to: 'programs#show_live'
  end

  get '/contact', to: 'contacts#public_form', as: 'contact_public'
  get '/contact/report', to: 'contacts#public_report_form', as: 'contact_public_report'
  post '/contact/post', to: 'contacts#public_post', as: 'contact_public_post'
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :message, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

=begin
  before_action :require_admin_authenticate, except: [
    :public_form,
    :public_report_form,
    :public_post
  ]
=end

  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  ## public actions (that is, users can see them)
  def public_form
    @category = 'contact'
    @prompt = 'ご感想やご質問があればどうぞ。'
    #@placeholder = ''
    @contact = Contact.new
    @contact.category = 'contact'
  end

  def public_report_form
    @category = 'report'
    @prompt = '登録されていない声優・番組があればご報告お願いします。'
    #@placeholder = '「」が登録されていません。'
    @contact = Contact.new
    @contact.category = 'report'
    @contact.message = <<~EOT
      登録されていない声優(複数記述可):


      登録されていない番組(複数記述可):


    EOT

    render :public_form
  end

  def public_post
    @contact = Contact.new(contact_params)
    if @contact.save
      thanks = (@contact.category == 'report' ? 'ご協力ありがとうございます。' : '')
      @notice = "送信しました。#{thanks}" 
      @alert = 'success'
    else
      @notice = 'エラー'
      @alert = 'warning'
    end
  end

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:category, :email, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.slim
= form_for @contact, html: { class: "form form-horizontal contact" } do |f|
  .form-group
    = f.label :category, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :category, :class => 'form-control'
    = f.error_span(:category)
  .form-group
    = f.label :email, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :email, :class => 'form-control'
    = f.error_span(:email)
  .form-group
    = f.label :message, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :message, :class => 'form-control'
    = f.error_span(:message)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), contacts_path, :class => 'btn'

app/views/contacts/edit.html.slim
- model_class = Contact
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contacts/index.html.slim
- model_class = Contact
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:category)
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:message)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @contacts.each do |contact|
      tr
        td= link_to contact.id, contact_path(contact)
        td= contact.category
        td= contact.email
        td= contact.message
        td=l contact.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_contact_path(contact), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), contact_path(contact), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_contact_path, :class => 'btn btn-primary'

app/views/contacts/new.html.slim
- model_class = Contact
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contacts/public_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <%= @prompt %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <%= form_for @contact, url: contact_public_post_path, html: { class: 'form-horizontal' } do | f | %>
        <%= f.hidden_field :category %>
        <div claass="form-group">
          <div class="">
            <%= f.label :email, 'メールアドレス(任意)', class: 'control-label' %>
          </div>
          <div class="">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div claass="form-group">
          <div class="">
            <%= f.label :message, '内容', class: 'control-label' %>
          </div>
          <div class="">
            <%= f.text_area :message, class: 'form-control', rows: 6, resizable: true %>
          </div>
        </div>
        <div style="margin-top: 10px; text-align: right">
          <%= f.submit '送信', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/public_post.html.erb
<p class="alert alert-<%= @alert %>"><%= @notice %></p>

<%= link_to 'トップ', root_path %>

app/views/contacts/show.html.slim
- model_class = Contact
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:category) + ':'
  br
  = @contact.category
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @contact.email
p
  strong= model_class.human_attribute_name(:message) + ':'
  br
  = @contact.message

= link_to t('.back', :default => t("helpers.links.back")), contacts_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_contact_path(@contact), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), contact_path(@contact), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'