config/routes.rb
module ::KoeNicoRoutesExtender
  def get_with_finished(path, *args, **kwds)
    fkwds = {}
    fkwds[:action] = "#{kwds[:action]}_finished"
    fkwds[:as] = "#{kwds[:as]}_finished" if kwds[:as]
    get path, *args, **kwds
    get "#{path}/finished", *args, **(kwds.merge(fkwds))
  end
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root controller: 'top_page', action: 'index'

  scope '/programs', controller: 'programs', as: 'programs' do

    extend ::KoeNicoRoutesExtender

    get_with_finished '/',          action: 'index'
    get_with_finished '/favorites', action: 'index_favorites'

    #get '/all',       action: 'index_all'

    get_with_finished '/v/:names',
      action: 'search_by_voiceactors',
      as: :search_by_voiceactors

    get_with_finished '/tag/:tag',
      action: 'search_by_tag',
      as: :search_by_tag
  end

  get '/voiceactors', to: 'voiceactor#index'

  # TODO: make restful
  get    '/profile/favorites', to: 'users#list_favorites'
  put    '/profile/favorites/:name', to: 'users#add_favorite', as: 'profile_favorite'
  delete '/profile/favorites/:name', to: 'users#delete_favorite'

  scope '/admin' do
    get  'manage_voiceactors/import_yaml', to: 'manage_voiceactors#import_yaml_form'
    post 'manage_voiceactors/import_yaml', to: 'manage_voiceactors#import_yaml'

    resources :manage_voiceactors
    resources :contacts

    get 'programs/:live_id', to: 'programs#show_live'
  end

  get '/contact', to: 'contacts#public_form', as: 'contact_public'
  get '/contact/report', to: 'contacts#public_report_form', as: 'contact_public_report'
  post '/contact/post', to: 'contacts#public_post', as: 'contact_public_post'
end

app/models/manage_voiceactor.rb
class ManageVoiceactor < Voiceactor
  #self.table_name = 'voiceactors'
end

app/controllers/manage_voiceactors_controller.rb
class ManageVoiceactorsController < ApplicationController

  before_action :set_manage_voiceactor, only: [:show, :edit, :update, :destroy]

  # GET /manage_voiceactors
  # GET /manage_voiceactors.json
  def index
    @manage_voiceactors = ManageVoiceactor.all.order('id desc')
  end

  # GET /manage_voiceactors/1
  # GET /manage_voiceactors/1.json
  def show
    respond_to{| f |
      f.html
      f.json
      f.yaml{ render text: @manage_voiceactor.to_yaml }
    }
  end

  # GET /manage_voiceactors/new
  def new
    @manage_voiceactor = ManageVoiceactor.new
  end

  # GET /manage_voiceactors/1/edit
  def edit
  end

  # POST /manage_voiceactors
  # POST /manage_voiceactors.json
  def create
    @manage_voiceactor = ManageVoiceactor.new(manage_voiceactor_params)
    #@voiceactor = Voiceactor.new(manage_voiceactor_params)

    LiveProgram.search_missing_voiceactor(@manage_voiceactor.name).each{| program |
      program.voiceactors += [@manage_voiceactor]
      program.save
    }

    respond_to do |format|
      if @manage_voiceactor.save
        format.html { redirect_to @manage_voiceactor, notice: 'Manage voiceactor was successfully created.' }
        format.json { render :show, status: :created, location: @manage_voiceactor }
      else
        format.html { render :new }
        format.json { render json: @manage_voiceactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manage_voiceactors/1
  # PATCH/PUT /manage_voiceactors/1.json
  def update
    respond_to do |format|
      if @manage_voiceactor.update(manage_voiceactor_params)
        format.html { redirect_to @manage_voiceactor, notice: 'Manage voiceactor was successfully updated.' }
        format.json { render :show, status: :ok, location: @manage_voiceactor }
      else
        format.html { render :edit }
        format.json { render json: @manage_voiceactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manage_voiceactors/1
  # DELETE /manage_voiceactors/1.json
  def destroy
    @manage_voiceactor.destroy
    respond_to do |format|
      format.html { redirect_to manage_voiceactors_url, notice: 'Manage voiceactor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import_yaml_form
  end

  def import_yaml
    messages = Voiceactor.import_errata_from_yaml(params[:yaml])
    render plain: messages.join("\n")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manage_voiceactor
      @manage_voiceactor = ManageVoiceactor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manage_voiceactor_params
      params.require(:manage_voiceactor).permit(:name, :furigana, :gender, :abstract)
    end
end

app/helpers/manage_voiceactors_helper.rb
module ManageVoiceactorsHelper
end

app/views/manage_voiceactors/_form.html.erb
<%= form_for @manage_voiceactor, :html => { :class => "form-horizontal manage_voiceactor" } do |f| %>

  <% if @manage_voiceactor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@manage_voiceactor.errors.count, "error") %> prohibited this manage_voiceactor from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @manage_voiceactor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :furigana, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :furigana, :class => 'form-control' %>
    </div>
    <%=f.error_span(:furigana) %>
  </div>
  <div class="form-group">
    <%= f.label :gender, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :gender, :class => 'form-control' %>
    </div>
    <%=f.error_span(:gender) %>
  </div>
  <div class="form-group">
    <%= f.label :abstract, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :abstract, :class => 'form-control', :size => "x5" %>
    </div>
    <%=f.error_span(:abstract) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                manage_voiceactors_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/manage_voiceactors/edit.html.erb
<%- model_class = ManageVoiceactor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/manage_voiceactors/import_yaml_form.html.erb
<%= form_tag manage_voiceactors_import_yaml_path, method: 'POST', id:'the-form' do%>
<%= text_area_tag :yaml %>
<% end %>

app/views/manage_voiceactors/index.html.erb
<%- model_class = ManageVoiceactor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<style> tr:nth-child(n+10){ display : none } </style>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:furigana) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:abstract) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @manage_voiceactors.each_with_index do |manage_voiceactor,i| %>
      <tr>
        <td><%= link_to manage_voiceactor.id, manage_voiceactor_path(manage_voiceactor) %></td>
        <td><%= manage_voiceactor.name %></td>
        <td><%= manage_voiceactor.furigana %></td>
        <td><%= manage_voiceactor.gender %></td>
        <td><%= manage_voiceactor.abstract %></td>
        <td><%=l manage_voiceactor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_manage_voiceactor_path(manage_voiceactor), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      manage_voiceactor_path(manage_voiceactor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_manage_voiceactor_path,
            :class => 'btn btn-primary' %>

app/views/manage_voiceactors/new.html.erb
<%- model_class = ManageVoiceactor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/manage_voiceactors/show.html.erb
<%- model_class = ManageVoiceactor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @manage_voiceactor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:furigana) %>:</strong></dt>
  <dd><%= @manage_voiceactor.furigana %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @manage_voiceactor.gender %></dd>
  <dt><strong><%= model_class.human_attribute_name(:abstract) %>:</strong></dt>
  <dd><%= @manage_voiceactor.abstract %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              manage_voiceactors_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_manage_voiceactor_path(@manage_voiceactor), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              manage_voiceactor_path(@manage_voiceactor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>