config/routes.rb
module ::KoeNicoRoutesExtender
  def get_with_finished(path, *args, **kwds)
    fkwds = {}
    fkwds[:action] = "#{kwds[:action]}_finished"
    fkwds[:as] = "#{kwds[:as]}_finished" if kwds[:as]
    get path, *args, **kwds
    get "#{path}/finished", *args, **(kwds.merge(fkwds))
  end
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root controller: 'top_page', action: 'index'

  scope '/programs', controller: 'programs', as: 'programs' do

    extend ::KoeNicoRoutesExtender

    get_with_finished '/',          action: 'index'
    get_with_finished '/favorites', action: 'index_favorites'

    #get '/all',       action: 'index_all'

    get_with_finished '/v/:names',
      action: 'search_by_voiceactors',
      as: :search_by_voiceactors

    get_with_finished '/tag/:tag',
      action: 'search_by_tag',
      as: :search_by_tag
  end

  get '/voiceactors', to: 'voiceactor#index'

  # TODO: make restful
  get    '/profile/favorites', to: 'users#list_favorites'
  put    '/profile/favorites/:name', to: 'users#add_favorite', as: 'profile_favorite'
  delete '/profile/favorites/:name', to: 'users#delete_favorite'

  scope '/admin' do
    get  'manage_voiceactors/import_yaml', to: 'manage_voiceactors#import_yaml_form'
    post 'manage_voiceactors/import_yaml', to: 'manage_voiceactors#import_yaml'

    resources :manage_voiceactors
    resources :contacts

    get 'programs/:live_id', to: 'programs#show_live'
  end

  get '/contact', to: 'contacts#public_form', as: 'contact_public'
  get '/contact/report', to: 'contacts#public_report_form', as: 'contact_public_report'
  post '/contact/post', to: 'contacts#public_post', as: 'contact_public_post'
end

app/views/common/_footer.html.erb
<div class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <ul class="footer-items-list">
          <li><%= link_to '登録されていない声優・番組を報告', contact_public_report_path %></li>
          <li><%= link_to '問い合わせ', contact_public_path %></li>
          <li><%= link_to 'CC', '/cc.html', data: {'turbolinks' => 'false'} %></li>
        </ul>
      </div>
    </div>
    <div class="footer-copyright">
      <p>
        2016 <%= link_to '@leroy_seiyuu', 'https://twitter.com/leroy_seiyuu' %>
      </p>
    </div>
  </div>
</div>

app/views/common/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to '声ニコ', root_path, class: 'header-link-to-top' %></li>
      <li><%= link_to 'お気に入り', programs_favorites_path %></li>
      <li><%= link_to '番組一覧', programs_path %></li>
      <li><%= link_to '声優検索', profile_favorites_path %></li>
    </ul>
  </div>
</nav>